//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayStudio.Common {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrintRibbonControllerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrintRibbonControllerResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RailwayStudio.Common.PrintRibbonControllerResources", typeof(PrintRibbonControllerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ClosePreview {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ClosePreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ClosePreviewLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ClosePreviewLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_Customize {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Customize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_CustomizeLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_CustomizeLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_Document {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_DocumentMap {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_DocumentMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_DocumentMapLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_DocumentMapLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_EditPageHF {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_EditPageHF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_EditPageHFLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_EditPageHFLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportCsv {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportCsv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportCsvLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportCsvLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportFile {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportFileLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportFileLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportGraphic {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportGraphicLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportGraphicLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportHtm {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportHtm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportHtmLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportHtmLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportMht {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportMht", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportMhtLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportMhtLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportPdf {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportPdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportPdfLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportPdfLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportRtf {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportRtf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportRtfLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportRtfLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportTxt {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportTxt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportTxtLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportTxtLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportXls {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportXls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportXlsLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportXlsLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportXlsx {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportXlsx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ExportXlsxLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ExportXlsxLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_FillBackground {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_FillBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_FillBackgroundLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_FillBackgroundLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_Find {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_FindLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_FindLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_HandTool {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_HandTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_Magnifier {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Magnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_MultiplePages {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_MultiplePages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_MultiplePagesLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_MultiplePagesLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_Open {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_OpenLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_OpenLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PageMargins {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageMargins", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PageMarginsLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PageMarginsModerate {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsModerate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PageMarginsNarrow {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PageMarginsNormal {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PageMarginsWide {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsWide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PageOrientation {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageOrientation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PageOrientationLandscape {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLandscape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PageOrientationLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PageOrientationPortrait {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageOrientationPortrait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PageSetupDialog {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PageSetupDialog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PaperKind_A3 {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PaperKind_A4 {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PaperKind_A5 {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PaperKind_A6 {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PaperKind_Executive {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Executive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PaperKind_Legal {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Legal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PaperKind_Letter {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Letter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PaperKind_Tabloid {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Tabloid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PaperSize {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperSize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PaperSizeLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PaperSizeLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_Parameters {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Parameters", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ParametersLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ParametersLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_Pointer {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Pointer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_Print {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PrintDirect {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PrintDirect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PrintDirectLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PrintDirectLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PrintLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PrintLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PrintSetup {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PrintSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_PrintSetupLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PrintSetupLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_Save {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SaveLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SaveLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_Scale {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Scale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ScaleLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ScaleLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendCsv {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendCsv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendCsvLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendCsvLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendFile {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendFileLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendFileLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendGraphic {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendGraphicLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendGraphicLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendMht {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendMht", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendMhtLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendMhtLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendPdf {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendPdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendPdfLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendPdfLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendRtf {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendRtf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendRtfLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendRtfLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendTxt {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendTxt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendTxtLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendTxtLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendXls {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendXls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendXlsLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendXlsLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendXlsx {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendXlsx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_SendXlsxLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_SendXlsxLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ShowFirstPage {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ShowFirstPageLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPageLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ShowLastPage {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ShowLastPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ShowLastPageLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ShowLastPageLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ShowNextPage {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ShowNextPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ShowNextPageLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ShowNextPageLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ShowPrevPage {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ShowPrevPageLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPageLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_Thumbnails {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Thumbnails", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ThumbnailsLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ThumbnailsLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_Watermark {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Watermark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_WatermarkLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_WatermarkLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_Zoom {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ZoomIn {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ZoomIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ZoomInLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ZoomInLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ZoomLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ZoomLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ZoomOut {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ZoomOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonPrintPreview_ZoomOutLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_ZoomOutLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
