//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rwm.Otc.Themes.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rwm.Otc.Themes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///    &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B01_00_00_0 {
            get {
                return ResourceManager.GetString("B01_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///    &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B01_00_00_1 {
            get {
                return ResourceManager.GetString("B01_00_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 19,31 L 11,31 L 0,20 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 6,20 L 12,26 L 10,28 L 4,22 z &quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;
        ///.
        /// </summary>
        internal static string B02_00_00_0 {
            get {
                return ResourceManager.GetString("B02_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 19,31 L 11,31 L 0,20 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 6,20 L 12,26 L 10,28 L 4,22 z &quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;
        ///.
        /// </summary>
        internal static string B02_00_00_1 {
            get {
                return ResourceManager.GetString("B02_00_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot;  d=&quot;M 0,12 L 27,12 L 27,19 L 0,19 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot;  d=&quot;M 24,7 L 27,7 L 27,24 L 24,24 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B03_00_00_0 {
            get {
                return ResourceManager.GetString("B03_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot;  d=&quot;M 0,12 L 27,12 L 27,19 L 0,19 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot;  d=&quot;M 24,7 L 27,7 L 27,24 L 24,24 z &quot; /&gt;
        ///    
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B03_00_00_1 {
            get {
                return ResourceManager.GetString("B03_00_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- Abzweig unten links --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 31,19 L 24,19 L 12,31 L 20,31 L 31,20 z &quot; /&gt;
        ///  &lt;!-- Au [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B10_00_00_0 {
            get {
                return ResourceManager.GetString("B10_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///   &lt;g&gt;
        ///      &lt;!-- Track --&gt;
        ///      &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///      &lt;!-- Ausleuchtung grau --&gt;
        ///      &lt;path stroke=&quot;rgb(0,255,255)&quot; fill=&quot;rgb(0,255,255)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///      &lt;!-- Abzweig unten links --&gt;
        ///      &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 31,19 L 24,19 L 12,31 L 20,31 L 31,20 z  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B10_01_00_0 {
            get {
                return ResourceManager.GetString("B10_01_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///   &lt;g&gt;
        ///      &lt;!-- Track --&gt;
        ///      &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///      &lt;!-- Ausleuchtung grau --&gt;
        ///      &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///      &lt;!-- Abzweig unten links --&gt;
        ///      &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 31,19 L 24,19 L 12,31 L 20,31 L 31,20 z  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B10_01_00_1 {
            get {
                return ResourceManager.GetString("B10_01_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- Abzweig unten links --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 31,19 L 24,19 L 12,31 L 20,31 L 31,20 z &quot; /&gt;
        ///  &lt;!-- Au [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B10_02_00_0 {
            get {
                return ResourceManager.GetString("B10_02_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- Abzweig unten links --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 31,19 L 24,19 L 12,31 L 20,31 L 31,20 z &quot; /&gt;
        ///  &lt;!-- Au [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B10_02_00_1 {
            get {
                return ResourceManager.GetString("B10_02_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- Abzweig unten rechts --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,19 L 7,19 L 19,31 L 15,31 L 11,31 L 0,20 z &quot; /&gt;
        ///  &lt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B11_00_00_0 {
            get {
                return ResourceManager.GetString("B11_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(0,255,255)&quot; fill=&quot;rgb(0,255,255)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- Abzweig unten rechts --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,19 L 7,19 L 19,31 L 15,31 L 11,31 L 0,20 z &quot; /&gt;
        ///  &lt;!--  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B11_01_00_0 {
            get {
                return ResourceManager.GetString("B11_01_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- Abzweig unten rechts --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,19 L 7,19 L 19,31 L 15,31 L 11,31 L 0,20 z &quot; /&gt;
        ///  &lt;!--  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B11_01_00_1 {
            get {
                return ResourceManager.GetString("B11_01_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- Abzweig unten rechts --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,19 L 7,19 L 19,31 L 15,31 L 11,31 L 0,20 z &quot; /&gt;
        ///  &lt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B11_02_00_0 {
            get {
                return ResourceManager.GetString("B11_02_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- Abzweig unten rechts --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,19 L 7,19 L 19,31 L 15,31 L 11,31 L 0,20 z &quot; /&gt;
        ///  &lt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B11_02_00_1 {
            get {
                return ResourceManager.GetString("B11_02_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 24,12 L 31,12 L 31,19 L 24,19 z &quot; /&gt;
        ///    &lt;!-- Abzweig unten links --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 31,19 L 24,19 L 12,31 L 20,31 L 31,20 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung Abzweig unten links grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 19,26 L 25,20 L 27,22 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B12_00_00_0 {
            get {
                return ResourceManager.GetString("B12_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 24,12 L 31,12 L 31,19 L 24,19 z &quot; /&gt;
        ///    &lt;!-- Abzweig unten links --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 31,19 L 24,19 L 12,31 L 20,31 L 31,20 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung Abzweig unten links grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 19,26 L 25,20 L 27,22 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B12_01_00_0 {
            get {
                return ResourceManager.GetString("B12_01_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 24,12 L 31,12 L 31,19 L 24,19 z &quot; /&gt;
        ///    &lt;!-- Abzweig unten links --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 31,19 L 24,19 L 12,31 L 20,31 L 31,20 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung Abzweig unten links grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 19,26 L 25,20 L 27,22 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B12_01_00_1 {
            get {
                return ResourceManager.GetString("B12_01_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 24,12 L 31,12 L 31,19 L 24,19 z &quot; /&gt; 
        ///  &lt;!-- Abzweig unten links --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 31,19 L 24,19 L 12,31 L 20,31 L 31,20 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung Abzweig unten links grau --&gt;
        ///    &lt;path stroke=&quot;rgb(0,255,255)&quot; fill=&quot;rgb(0,255,255)&quot; d=&quot;M 19,26 L 25,20 L 27,22 L 21 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B12_02_00_0 {
            get {
                return ResourceManager.GetString("B12_02_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 24,12 L 31,12 L 31,19 L 24,19 z &quot; /&gt; 
        ///  &lt;!-- Abzweig unten links --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 31,19 L 24,19 L 12,31 L 20,31 L 31,20 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung Abzweig unten links grau --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 19,26 L 25,20 L 27,22 L 21 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B12_02_00_1 {
            get {
                return ResourceManager.GetString("B12_02_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- Abzweig unten links --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 31,19 L 24,19 L 12,31 L 20,31 L 31,20 z &quot; /&gt;
        ///  &lt;!-- Au [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B13_00_00_0 {
            get {
                return ResourceManager.GetString("B13_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(0,255,255)&quot; fill=&quot;rgb(0,255,255)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- Abzweig unten links --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 31,19 L 24,19 L 12,31 L 20,31 L 31,20 z &quot; /&gt;
        ///  &lt;!-- Ausleu [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B13_01_00_0 {
            get {
                return ResourceManager.GetString("B13_01_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- Abzweig unten links --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 31,19 L 24,19 L 12,31 L 20,31 L 31,20 z &quot; /&gt;
        ///  &lt;!-- Ausleu [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B13_01_00_1 {
            get {
                return ResourceManager.GetString("B13_01_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- Abzweig unten links --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 31,19 L 24,19 L 12,31 L 20,31 L 31,20 z &quot; /&gt;
        ///  &lt;!-- Au [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B13_02_00_0 {
            get {
                return ResourceManager.GetString("B13_02_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- Abzweig unten links --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 31,19 L 24,19 L 12,31 L 20,31 L 31,20 z &quot; /&gt;
        ///  &lt;!-- Au [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B13_02_00_1 {
            get {
                return ResourceManager.GetString("B13_02_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- Abzweig unten links --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 31,19 L 24,19 L 12,31 L 20,31 L 31,20 z &quot; /&gt;
        ///  &lt;!-- Au [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B13_03_00_0 {
            get {
                return ResourceManager.GetString("B13_03_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- Abzweig unten links --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 31,19 L 24,19 L 12,31 L 20,31 L 31,20 z &quot; /&gt;
        ///  &lt;!-- Au [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B13_03_00_1 {
            get {
                return ResourceManager.GetString("B13_03_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;64&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;!-- Gerade --&gt; 
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 63,12 L  63,19 L 0,19 z &quot; /&gt;
        ///    &lt;!-- Ausleuchtung gerade links gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///    &lt;!-- Ausleuchtung gerade rechts gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 40,14 L 5 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B15_00_00_0 {
            get {
                return ResourceManager.GetString("B15_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;64&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;!-- Gerade --&gt; 
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 63,12 L  63,19 L 0,19 z &quot; /&gt;
        ///    &lt;!-- Ausleuchtung gerade links gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(0,255,255)&quot; fill=&quot;rgb(0,255,255)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///    &lt;!-- Ausleuchtung gerade rechts gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(0,255,255)&quot; fill=&quot;rgb(0,255,255)&quot; d=&quot;M 40,14 L 55,14 L 5 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B15_01_00_0 {
            get {
                return ResourceManager.GetString("B15_01_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;64&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;!-- Gerade --&gt; 
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 63,12 L  63,19 L 0,19 z &quot; /&gt;
        ///    &lt;!-- Ausleuchtung gerade links gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///    &lt;!-- Ausleuchtung gerade rechts gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 40,14 L 55,14 L 5 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B15_01_00_1 {
            get {
                return ResourceManager.GetString("B15_01_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;64&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;!-- links mitte rechts unten --&gt; 
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 25,12 L 51,31 L 43,31 L 26,19 L 0,19 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 25,12 L 38,12 L 38,19 L 25,19 z &quot; /&gt;
        ///    &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(0,255,255)&quot; fill=&quot;rgb(0,255,255)&quot; d=&quot;M 8,14 L 25,14 L 41,25 L 39,27 L 25,17 L 8,17 z &quot; / [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B15_02_00_0 {
            get {
                return ResourceManager.GetString("B15_02_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;64&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;!-- links mitte rechts unten --&gt; 
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 25,12 L 51,31 L 43,31 L 26,19 L 0,19 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 25,12 L 38,12 L 38,19 L 25,19 z &quot; /&gt;
        ///    &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 25,14 L 41,25 L 39,27 L 25,17 L 8,17 z &quot; /&gt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B15_02_00_1 {
            get {
                return ResourceManager.GetString("B15_02_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,5 L 4,2 L 15,2 L 18,5 L 18,6 L 15,9 L 4,9 L 1,6 z &quot; /&gt;
        ///  &lt;!-- Gru [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B20_00_00_0 {
            get {
                return ResourceManager.GetString("B20_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,5 L 4,2 L 15,2 L 18,5 L 18,6 L 15,9 L 4,9 L 1,6 z &quot; /&gt;
        ///  &lt;!-- Gru [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B20_01_00_0 {
            get {
                return ResourceManager.GetString("B20_01_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,5 L 4,2 L 15,2 L 18,5 L 18,6 L 15,9 L 4,9 L 1,6 z &quot; /&gt;
        ///  &lt;!-- Gruene  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B20_01_00_1 {
            get {
                return ResourceManager.GetString("B20_01_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,5 L 4,2 L 15,2 L 18,5 L 18,6 L 15,9 L 4,9 L 1,6 z &quot; /&gt;
        ///  &lt;!-- Gru [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B20_02_00_0 {
            get {
                return ResourceManager.GetString("B20_02_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,5 L 4,2 L 15,2 L 18,5 L 18,6 L 15,9 L 4,9 L 1,6 z &quot; /&gt;
        ///  &lt;!-- Gruene  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B20_02_00_1 {
            get {
                return ResourceManager.GetString("B20_02_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,5 L 4,2 L 22,2 L 25,5 L 25,6 L 22,9 L 4,9 L 1,6 z &quot; /&gt;
        ///  &lt;!-- Gru [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B21_00_00_0 {
            get {
                return ResourceManager.GetString("B21_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,5 L 4,2 L 22,2 L 25,5 L 25,6 L 22,9 L 4,9 L 1,6 z &quot; /&gt;
        ///  &lt;!-- Gru [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B21_01_00_0 {
            get {
                return ResourceManager.GetString("B21_01_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,5 L 4,2 L 22,2 L 25,5 L 25,6 L 22,9 L 4,9 L 1,6 z &quot; /&gt;
        ///  &lt;!-- Gruene  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B21_01_00_1 {
            get {
                return ResourceManager.GetString("B21_01_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,5 L 4,2 L 22,2 L 25,5 L 25,6 L 22,9 L 4,9 L 1,6 z &quot; /&gt;
        ///  &lt;!-- Gru [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B21_02_00_0 {
            get {
                return ResourceManager.GetString("B21_02_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,5 L 4,2 L 22,2 L 25,5 L 25,6 L 22,9 L 4,9 L 1,6 z &quot; /&gt;
        ///  &lt;!-- Gruene  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B21_02_00_1 {
            get {
                return ResourceManager.GetString("B21_02_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,5 L 4,2 L 22,2 L 25,5 L 25,6 L 22,9 L 4,9 L 1,6 z &quot; /&gt;
        ///  &lt;!-- Gru [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B21_03_00_0 {
            get {
                return ResourceManager.GetString("B21_03_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,5 L 4,2 L 22,2 L 25,5 L 25,6 L 22,9 L 4,9 L 1,6 z &quot; /&gt;
        ///  &lt;!-- Gruene  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B21_03_00_1 {
            get {
                return ResourceManager.GetString("B21_03_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,1 L 11,1 L 15,5 L 16,6 L 16,10 L 6,10 L 1,5 z &quot; /&gt;
        ///  &lt;!-- Gruene  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B22_00_00_0 {
            get {
                return ResourceManager.GetString("B22_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,1 L 11,1 L 15,5 L 16,6 L 16,10 L 6,10 L 1,5 z &quot; /&gt;
        ///  &lt;!-- Gruene  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B22_01_00_0 {
            get {
                return ResourceManager.GetString("B22_01_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,1 L 11,1 L 15,5 L 16,6 L 16,10 L 6,10 L 1,5 z &quot; /&gt;
        ///  &lt;!-- Gruene Lamp [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B22_01_00_1 {
            get {
                return ResourceManager.GetString("B22_01_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,1 L 11,1 L 15,5 L 16,6 L 16,10 L 6,10 L 1,5 z &quot; /&gt;
        ///  &lt;!-- Gruene  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B22_02_00_0 {
            get {
                return ResourceManager.GetString("B22_02_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,1 L 11,1 L 15,5 L 16,6 L 16,10 L 6,10 L 1,5 z &quot; /&gt;
        ///  &lt;!-- Gruene Lamp [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B22_02_00_1 {
            get {
                return ResourceManager.GetString("B22_02_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,1 L 11,1 L 15,5 L 16,6 L 16,10 L 6,10 L 1,5 z &quot; /&gt;
        ///  &lt;!-- Gruene  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B22_03_00_0 {
            get {
                return ResourceManager.GetString("B22_03_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 1,1 L 11,1 L 15,5 L 16,6 L 16,10 L 6,10 L 1,5 z &quot; /&gt;
        ///  &lt;!-- Gruene Lamp [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B22_03_00_1 {
            get {
                return ResourceManager.GetString("B22_03_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 3,1 L 14,1 L 16,3 L 16,5 L 16,6 L 16,8 L 14,10 L 3,10 L 1,8 L 1,3 z  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B23_00_00_0 {
            get {
                return ResourceManager.GetString("B23_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 3,1 L 14,1 L 16,3 L 16,5 L 16,6 L 16,8 L 14,10 L 3,10 L 1,8 L 1,3 z  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B23_01_00_0 {
            get {
                return ResourceManager.GetString("B23_01_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 3,1 L 14,1 L 16,3 L 16,5 L 16,6 L 16,8 L 14,10 L 3,10 L 1,8 L 1,3 z &quot; /&gt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B23_01_00_1 {
            get {
                return ResourceManager.GetString("B23_01_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung grau --&gt;
        ///    &lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 3,1 L 14,1 L 16,3 L 16,5 L 16,6 L 16,8 L 14,10 L 3,10 L 1,8 L 1,3 z  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B23_02_00_0 {
            get {
                return ResourceManager.GetString("B23_02_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///  &lt;!-- Track --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot; /&gt;
        ///  &lt;!-- Ausleuchtung gelb --&gt;
        ///    &lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot; /&gt;
        ///  &lt;!-- signal --&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 3,1 L 14,1 L 16,3 L 16,5 L 16,6 L 16,8 L 14,10 L 3,10 L 1,8 L 1,3 z &quot; /&gt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B23_02_00_1 {
            get {
                return ResourceManager.GetString("B23_02_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;path stroke=&quot;rgb(0, 38, 255)&quot; fill=&quot;rgb(0, 38, 255)&quot; d=&quot;M 0,0 L 31,0 L 31,31 L 0,31 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(255, 255, 255)&quot; d=&quot;M 3,20 L 28,20 L 28,29 L 3,29 z &quot; /&gt;    
        ///    &lt;circle cx=&quot;16&quot; cy=&quot;10&quot; r=&quot;6&quot; stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(160, 160, 160)&quot; /&gt;
        ///    &lt;text x=&quot;5&quot; y=&quot;27&quot; font-family=&quot;sans-serif&quot; font-size=&quot;7px&quot; fill=&quot;black&quot;&gt;#NAME&lt;/text&gt;
        ///  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string B30_00_00_0 {
            get {
                return ResourceManager.GetString("B30_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;path stroke=&quot;rgb(0, 38, 255)&quot; fill=&quot;rgb(0, 38, 255)&quot; d=&quot;M 0,0 L 31,0 L 31,31 L 0,31 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(255, 255, 255)&quot; d=&quot;M 7,20 L 26,20 L 26,28 L 7,28 z &quot; /&gt;    
        ///    &lt;circle cx=&quot;16&quot; cy=&quot;11&quot; r=&quot;6&quot; stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(160, 160, 160)&quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B30_01_00_0 {
            get {
                return ResourceManager.GetString("B30_01_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;path stroke=&quot;rgb(0, 38, 255)&quot; fill=&quot;rgb(0, 38, 255)&quot; d=&quot;M 0,0 L 31,0 L 31,31 L 0,31 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(255, 255, 255)&quot; d=&quot;M 7,20 L 26,20 L 26,28 L 7,28 z &quot; /&gt;    
        ///    &lt;circle cx=&quot;16&quot; cy=&quot;11&quot; r=&quot;6&quot; stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(240, 0, 0)&quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B30_02_00_0 {
            get {
                return ResourceManager.GetString("B30_02_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;path stroke=&quot;rgb(255, 0, 0)&quot; fill=&quot;rgb(255, 0, 0)&quot; d=&quot;M 0,0 L 31,0 L 31,31 L 0,31 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(255, 255, 255)&quot; d=&quot;M 7,20 L 26,20 L 26,28 L 7,28 z &quot; /&gt;    
        ///    &lt;circle cx=&quot;16&quot; cy=&quot;11&quot; r=&quot;6&quot; stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(160, 160, 160)&quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B31_00_00_0 {
            get {
                return ResourceManager.GetString("B31_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;path stroke=&quot;rgb(255, 0, 0)&quot; fill=&quot;rgb(255, 0, 0)&quot; d=&quot;M 0,0 L 31,0 L 31,31 L 0,31 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(255, 255, 255)&quot; d=&quot;M 7,20 L 26,20 L 26,28 L 7,28 z &quot; /&gt;
        ///    &lt;circle cx=&quot;16&quot; cy=&quot;11&quot; r=&quot;6&quot; stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(160, 160, 160)&quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B31_01_00_0 {
            get {
                return ResourceManager.GetString("B31_01_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;path stroke=&quot;rgb(255, 0, 0)&quot; fill=&quot;rgb(255, 0, 0)&quot; d=&quot;M 0,0 L 31,0 L 31,31 L 0,31 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(255, 255, 255)&quot; d=&quot;M 7,20 L 26,20 L 26,28 L 7,28 z &quot; /&gt;    
        ///    &lt;circle cx=&quot;16&quot; cy=&quot;11&quot; r=&quot;6&quot; stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(240, 0, 0)&quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B31_02_00_0 {
            get {
                return ResourceManager.GetString("B31_02_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;path stroke=&quot;rgb(0, 255, 33)&quot; fill=&quot;rgb(0, 255, 33)&quot; d=&quot;M 0,0 L 31,0 L 31,31 L 0,31 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(255, 255, 255)&quot; d=&quot;M 7,20 L 26,20 L 26,28 L 7,28 z &quot; /&gt;    
        ///    &lt;circle cx=&quot;16&quot; cy=&quot;11&quot; r=&quot;6&quot; stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(160, 160, 160)&quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B32_00_00_0 {
            get {
                return ResourceManager.GetString("B32_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;path stroke=&quot;rgb(0, 255, 33)&quot; fill=&quot;rgb(0, 255, 33)&quot; d=&quot;M 0,0 L 31,0 L 31,31 L 0,31 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(255, 255, 255)&quot; d=&quot;M 7,20 L 26,20 L 26,28 L 7,28 z &quot; /&gt;    
        ///    &lt;circle cx=&quot;16&quot; cy=&quot;11&quot; r=&quot;6&quot; stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(160, 160, 160)&quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B32_01_00_0 {
            get {
                return ResourceManager.GetString("B32_01_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;path stroke=&quot;rgb(0, 255, 33)&quot; fill=&quot;rgb(0, 255, 33)&quot; d=&quot;M 0,0 L 31,0 L 31,31 L 0,31 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(255, 255, 255)&quot; d=&quot;M 7,20 L 26,20 L 26,28 L 7,28 z &quot; /&gt;    
        ///    &lt;circle cx=&quot;16&quot; cy=&quot;11&quot; r=&quot;6&quot; stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(240, 0, 0)&quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B32_02_00_0 {
            get {
                return ResourceManager.GetString("B32_02_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;path stroke=&quot;rgb(255, 216, 0)&quot; fill=&quot;rgb(255, 216, 0)&quot; d=&quot;M 0,0 L 31,0 L 31,31 L 0,31 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(255, 255, 255)&quot; d=&quot;M 7,20 L 26,20 L 26,28 L 7,28 z &quot; /&gt;    
        ///    &lt;circle cx=&quot;16&quot; cy=&quot;11&quot; r=&quot;6&quot; stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(160, 160, 160)&quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B33_00_00_0 {
            get {
                return ResourceManager.GetString("B33_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;path stroke=&quot;rgb(255, 216, 0)&quot; fill=&quot;rgb(255, 216, 0)&quot; d=&quot;M 0,0 L 31,0 L 31,31 L 0,31 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(255, 255, 255)&quot; d=&quot;M 7,20 L 26,20 L 26,28 L 7,28 z &quot; /&gt;    
        ///    &lt;circle cx=&quot;16&quot; cy=&quot;11&quot; r=&quot;6&quot; stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(160, 160, 160)&quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B33_01_00_0 {
            get {
                return ResourceManager.GetString("B33_01_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;path stroke=&quot;rgb(255, 216, 0)&quot; fill=&quot;rgb(255, 216, 0)&quot; d=&quot;M 0,0 L 31,0 L 31,31 L 0,31 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(255, 255, 255)&quot; d=&quot;M 7,20 L 26,20 L 26,28 L 7,28 z &quot; /&gt;    
        ///    &lt;circle cx=&quot;16&quot; cy=&quot;11&quot; r=&quot;6&quot; stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(240, 0, 0)&quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B33_02_00_0 {
            get {
                return ResourceManager.GetString("B33_02_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///&lt;g&gt;
        ///&lt;!--  Track  --&gt;
        ///&lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot;/&gt;
        ///&lt;!--  Ausleuchtung grau  --&gt;
        ///&lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot;/&gt;
        ///&lt;circle cx=&quot;16&quot; cy=&quot;5&quot; r=&quot;4&quot; stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(100, 0, 0)&quot;/&gt;
        ///&lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B34_00_00_0 {
            get {
                return ResourceManager.GetString("B34_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///&lt;g&gt;
        ///&lt;!--  Track  --&gt;
        ///&lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot;/&gt;
        ///&lt;!--  Ausleuchtung gelb  --&gt;
        ///&lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot;/&gt;
        ///&lt;circle cx=&quot;16&quot; cy=&quot;5&quot; r=&quot;4&quot; stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(255, 0, 0)&quot;/&gt;
        ///&lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B34_00_00_1 {
            get {
                return ResourceManager.GetString("B34_00_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///&lt;g&gt;
        ///&lt;!--  Track  --&gt;
        ///&lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot;/&gt;
        ///&lt;!--  Ausleuchtung grau  --&gt;
        ///&lt;path stroke=&quot;rgb(192,192,192)&quot; fill=&quot;rgb(192,192,192)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot;/&gt;
        ///&lt;circle cx=&quot;16&quot; cy=&quot;5&quot; r=&quot;4&quot; stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(255, 0, 0)&quot;/&gt;
        ///&lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string B34_00_01_0 {
            get {
                return ResourceManager.GetString("B34_00_01_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;32&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///&lt;g&gt;
        ///&lt;!--  Track  --&gt;
        ///&lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(0,0,0)&quot; d=&quot;M 0,12 L 31,12 L 31,19 L 0,19 z &quot;/&gt;
        ///&lt;!--  Ausleuchtung gelb  --&gt;
        ///&lt;path stroke=&quot;rgb(255,255,0)&quot; fill=&quot;rgb(255,255,0)&quot; d=&quot;M 8,14 L 23,14 L 23,17 L 8,17 z &quot;/&gt;
        ///&lt;circle cx=&quot;16&quot; cy=&quot;5&quot; r=&quot;4&quot; stroke=&quot;rgb(0, 0, 0)&quot; fill=&quot;rgb(100, 0, 0)&quot;/&gt;
        ///&lt;/g&gt;
        ///&lt;/svg&gt;
        ///.
        /// </summary>
        internal static string B34_00_01_1 {
            get {
                return ResourceManager.GetString("B34_00_01_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;64&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;none&quot; d=&quot;M 0,4 L 64,4 L 64,28 L 0,28 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(255,255,255)&quot; d=&quot;M 1,5 L 62,5 L 62,27 L 1,27 z &quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;
        ///.
        /// </summary>
        internal static string B40_00_00_0 {
            get {
                return ResourceManager.GetString("B40_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;64&quot; height=&quot;32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;none&quot; d=&quot;M 0,4 L 64,4 L 64,28 L 0,28 z &quot; /&gt;
        ///    &lt;path stroke=&quot;rgb(0,0,0)&quot; fill=&quot;rgb(255,255,255)&quot; d=&quot;M 1,5 L 62,5 L 62,27 L 1,27 z &quot; /&gt;
        ///  &lt;/g&gt;
        ///&lt;/svg&gt;
        ///.
        /// </summary>
        internal static string B41_00_00_0 {
            get {
                return ResourceManager.GetString("B41_00_00_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICO_IMAGE_ERROR_32 {
            get {
                object obj = ResourceManager.GetObject("ICO_IMAGE_ERROR_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
